#1
Algoritmo "teste processamento"

Var 

  x : inteiro
  y : real

Inicio

  x <- 5
  y <- 2 * x

  escreval(x)
  escreval(y)
Fimalgoritmo

------------------------------------------------------------------------------------------------------------------------

#2

Algoritmo "area"

Var 

  b1, b2, h, area : real
   
   

Inicio

  b1 <-6.0 
  b2 <- 8.0
  h  <- 5.0

 area <- (b1 + b2) / 2.0 * h
  escreval(area)
  
Fimalgoritmo

------------------------------------------------------------------------------------------------------------------------
#3

Algoritmo "teste"

Var

   a, b, resultado : inteiro

Inicio

      a <- 5
      b <- 2
      
      resultado <- a \ b
      escreval (resultado)

Fimalgoritmo

------------------------------------------------------------------------------------------------------------------------

#4
Algoritmo "teste"

Var

      a : real
      b : inteiro

Inicio

      a <- 5.3
      b <- Int(a)

      escreval (b)

Fimalgoritmo